import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import Request from "@/models/Request";
import { auth } from "@/lib/auth";
import mongoose from "mongoose";
import nodemailer from "nodemailer";

export async function POST(req) {
  try {
    // Connect to MongoDB
    await connectDB();

    // Get logged-in user from session headers
    const session = await auth.api.getSession({ headers: req.headers });
    if (!session?.user?.email || !session?.user?.name) {
      return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
    }

    // Get request body
    const body = await req.json(); // Read the full body
    const { targetEmail, subject, message } = body; 

    // 🚨 DEBUG FIX: Check and list missing fields
    const requiredFields = { targetEmail, subject, message };
    const missingFields = Object.keys(requiredFields).filter(key => !requiredFields[key]);
    
    if (missingFields.length > 0) {
      const errorMessage = `Missing required fields: ${missingFields.join(', ')}`;
      
      // 🚨 Console log for server debugging
      console.error(errorMessage, "Received body:", body); 
      
      // Return detailed error to the client
      return NextResponse.json(
        { 
          success: false, 
          message: errorMessage,
          missing: missingFields 
        }, 
        { status: 400 }
      );
    }
    // END DEBUG FIX

    // Fetch target dynamically (from users collection)
    const target = await mongoose.connection.db
      .collection("user")
      .findOne({ email: targetEmail, role: { $in: ["COUNSELLOR", "LAWYER"] } });

    if (!target) return NextResponse.json({ success: false, message: "Target not found" }, { status: 404 });

    // Create request in DB
    const newRequest = await Request.create({
      userName: session.user.name,
      userEmail: session.user.email,
      targetId: target._id.toString(),
      targetName: target.name,
      targetEmail: target.email,
      subject,
      message,
    });

    // Send email to target
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: { user: process.env.SMTP_EMAIL, pass: process.env.SMTP_PASS },
    });

    await transporter.sendMail({
      from: process.env.SMTP_EMAIL,
      to: target.email,
      // 🚨 FIX 2: Enhanced Subject
      subject: `URGENT Contact Request: Assistance Needed - ${subject}`, 
      // 🚨 FIX 3: Improved HTML Email Body
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 8px; background-color: #f9f9f9; }
            .header { border-bottom: 2px solid #5C6BC0; padding-bottom: 10px; margin-bottom: 20px; }
            .header h3 { color: #5C6BC0; margin: 0; }
            .details strong { display: inline-block; width: 100px; font-weight: 600; }
            .message-box { background-color: #fff; padding: 15px; border-radius: 4px; border: 1px solid #ddd; margin-top: 15px; }
            .footer { margin-top: 30px; font-size: 0.8em; color: #777; border-top: 1px solid #eee; padding-top: 10px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h3>New Request for Contact and Support</h3>
            </div>
            
            <p>Dear ${target.name || 'Professional'},</p>
            <p>
              A user is requesting urgent contact and support via the platform's directory. 
              The user, who has indicated they are experiencing difficulty or harassment, 
              requires assistance related to the subject below.
            </p>

            <div class="details">
              <p><strong>To:</strong> ${target.name} (${target.email})</p>
              <p><strong>From:</strong> ${session.user.name} (${session.user.email})</p>
              <p><strong>Subject:</strong> ${subject}</p>
            </div>

            <p>Please review the user's message below:</p>
            <div class="message-box">
              <p>
                ${message}
              </p>
            </div>

            <p style="margin-top: 25px;">
              **Immediate action is recommended.** Please log into your dedicated portal 
              dashboard as soon as possible to view the full request details, check the user's 
              security status, and initiate contact.
            </p>

            <div class="footer">
              <p>This message was automatically generated by the platform's request system.</p>
            </div>
          </div>
        </body>
        </html>
      `,
    });

    return NextResponse.json({ success: true, request: newRequest });
  } catch (err) {
    console.error("POST /api/requests failed:", err);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}

export async function GET(req) {
    try {
        await connectDB();

        // 🚨 SECURITY: Check if user is an OFFICER
        const session = await auth.api.getSession({ headers: req.headers });
     
        
        // Fetch ALL requests, ordered newest first
        const requests = await Request.find({})
            .sort({ createdAt: -1 })
            // We use the fields saved by the POST handler (userName, userEmail, etc.)
            .lean(); // Use .lean() for faster read performance

        return NextResponse.json(requests);
    } catch (err) {
        console.error("GET /api/requests failed:", err);
        return NextResponse.json({ success: false, error: err.message }, { status: 500 });
    }
}