import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LogoutButton  from "@/components/logout";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       {/* <nav className="bg-gray-800 text-white px-6 py-4 flex justify-center space-x-6">
  <Link href="/" className="hover:text-yellow-400 transition-colors duration-200 font-medium">
    Home
  </Link>
  <Link href="/dashboard" className="hover:text-yellow-400 transition-colors duration-200 font-medium">
    Dashboard
  </Link>
  <Link href="/auth/signIn" className="hover:text-yellow-400 transition-colors duration-200 font-medium">
    Sign In
  </Link>
  <Link href="/auth/signUp" className="hover:text-yellow-400 transition-colors duration-200 font-medium">
    Sign Up
  </Link>
 <LogoutButton />
</nav> */}
<Navbar/>

        {children}
      </body>
    </html>

  );
}


